name: Create GitHub Pages Branch

on:
  push:
    branches:
      - master

jobs:
  create_github_pages_branch:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git
        run: |
          git config --global user.email "cuentafrst@gmail.com"
          git config --global user.name "Armando"

      - name: Check out code
        uses: actions/checkout@v3

      - name: Create GitHub Pages Branch
        run: |
          git checkout -b gh-pages
          mkdir tmp && mv src/* tmp
          git rm -rf .
          mv tmp/* . && rm -rf tmp
          git add . && git commit -m "Move files"

      - name: Push GitHub Pages Branch
        uses: ad-m/github-push-action@v0.6.0
        with:
          branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
